import Head from 'next/head';
import About from '../components/About';
import NavBar from '../components/NavBar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mitch Moore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/waving.png" />
      </Head>

      <NavBar />

      <div className="w-full h-full flex justify-center min-h-screen">
        <About />
      </div>
    </div>
  );
}
